apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  containerName: 'compensation-svc'
  selector:
    namespaces:
      - ingress-basic
    labelSelectors:
      'app': 'compensation-svc'
  scheduler:
    cron: '@every 30s'