apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
spec:
  action: pod-kill
  mode: one
  duration: '60s'
  selector:
    namespaces:
      - ingress-basic
    labelSelectors:
      "app": "compensation-svc"
    #labelSelectors:
    #  namespace: ingress-basic
    #  "app": "compensation-svc"
  scheduler:
    cron: "@every 2m"