apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
spec:
  action: pod-failure
  mode: all
  value: ''
  duration: '1m'
  selector:
    namespaces:
      - ingress-basic
    labelSelectors:
      'app.kubernetes.io/instance': 'nginx-ingress'
  scheduler:
    cron: '@every 2m'